---
pipeline:
  stages:
    - name: Deploy to GCP
      container:
        image: google/cloud-sdk:latest
        entrypoint:
          - "sh"
          - "-c"
        commands:
          - "gcloud auth activate-service-account --key-file=C:\Users\rohit\Downloads\privatekey.json"
          - "gcloud config set project $(project_id)"
          - "cd terraform"
          - "terraform init"
          - "terraform apply -auto-approve"
